name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H "${{ secrets.EC2_HOST }}" >> ~/.ssh/known_hosts

    - name: Upload files to EC2
      run: |
        scp -r ./ ec2-user@${{ secrets.EC2_HOST }}:/home/ec2-user/app

    - name: Restart Application
      run: |
        ssh ec2-user@${{ secrets.EC2_HOST }} << EOF
          cd /home/ec2-user/app
          # Comandos para reiniciar la aplicación, ejemplo para Node.js:
          pm2 restart app.js || pm2 start app.js
        EOF
